# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.5"

# command to install dependencies
install: pip install tox

# tox environments to run
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8

# command to run tests, e.g. python setup.py test
script: tox

# startup faster
sudo: false
